name: Build, Test & Deploy NodeJs App

# Trigger workflow on any push to main (or remove 'branches' for all branches)
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 3Ô∏è‚É£ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5Ô∏è‚É£ Build NodeJs app
      - name: Build NodeJs app
        run: npx tsc

      # 6Ô∏è‚É£ Deploy via SCP
      - name: Copy dist to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "dist"
          target: "/var/www/mysportsorganizer/api"

      # üîÅ Install deps & restart PM2
      - name: Install & restart PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/mysportsorganizer/api
            npm install --production
            pm2 reload mysportsorganizer
